on pinoccio serial, show warnings for _unknown_ ports instead of known
Previously:

	$ pinoccio serial -d foo

	events.js:72
		throw er; // Unhandled 'error' event
		      ^
	Error: Cannot open foo
	$ pinoccio serial -d /dev/ttyACM0
	device  /dev/ttyACM0 may not be a pinoccio or connected. ill try and connect anyway.

Now the warning is correctly shown when specifying a serial port that was not
detected as a Pinoccio.

	$ pinoccio serial -d foo
	device  foo may not be a pinoccio or connected. ill try and connect anyway.

	events.js:72
		throw er; // Unhandled 'error' event
		      ^